### ISSUE TITLE
why not support the n parameter?

### ISSUE THREAD

**Issue by BaiMoHan** [ModelTC/lightllm#4]

**Comment by hiworldwzj** [comment]
@BaiMoHan Thank you for your question, At the beginning, Lightllm only had the core part of model inference and did not have an HTTP server component. It was mainly designed for chat scenarios and supporting n parameters may cause a decrease in the number of concurrent service users. Additionally, in order to keep the implementation simple enough, this feature was not supported. However, if this feature is very common and necessary, a high-performance implementation may be considered in the future.
